FROM openjdk:11-jre-slim

EXPOSE 8089
ARG APP_NAME=eventsProject-1.0.0-SNAPSHOT
ARG SPRING_PROFILES_ACTIVE=dev
ENV APP_NAME $APP_NAME
ENV SPRING_PROFILES_ACTIVE $SPRING_PROFILES_ACTIVE
VOLUME /app
ADD target/eventsProject-1.0.0-SNAPSHOT.jar /app.jar
WORKDIR /app
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=$SPRING_PROFILES_ACTIVE", "/app.jar"]
